### ISSUE TITLE
Can not import beer profile.

### ISSUE THREAD

**Issue by gieljnssns** [jeroen79/esp-brew-engine#42]
When trying to import a beer profile, I can select an xml file(from brewfather), but when I press `import` I get `Please import beer first!`
![Scherm­afbeelding 2024-10-26 om 16 27 30](https://github.com/user-attachments/assets/905f0c8b-2e0b-4578-bc9e-a7c9a8bd6202)

**Comment by jeroen79** [comment]
Hi, are you willing to attach the xml file?, or a dummy recipe that also has the issue?

**Comment by gieljnssns** [comment]
[Brewfather_BeerXML_SugarDaddyKhalua_20241026.xml.zip](https://github.com/user-attachments/files/17533422/Brewfather_BeerXML_SugarDaddyKhalua_20241026.xml.zip)

**Comment by gieljnssns** [comment]
Any updates on this?

**Comment by jeroen79** [comment]
I have created a new release (1.5.0) can u please verify the fix?

**Comment by gieljnssns** [comment]
Thanks! I’ll try this in 2 days, I ‘ll let you know…

**Comment by gieljnssns** [comment]
Thanks a lot, I can import my xml file now.
